module.exports = [
    {
      item_name: "Direct Deposit",
      amount: 100,
      date: "September 30",
      from: "Pusruit",
      category: "Income",
    },
    {
        item_name: "Utility Bill",
        amount: -200,
        date: " October 5",
        from: "Con Edison",
        category: "Utilites",
      },
      {
        item_name: "Bonus Check",
        amount: 3000,
        date: " October 7",
        from: "Pursuit",
        category: "Income",
      },
      {
        item_name: "Gym Membership",
        amount: -30,
        date: " October 22",
        from: "Planet Fitness",
        category: "Subscriptions",
      },
      {
        item_name: "Netflix",
        amount: -15,
        date: " October 22",
        from: "Netflix",
        category: "Subscriptions",
      },
      {
        item_name: "Groceries",
        amount: -250,
        date: " November 1",
        from: "BJ's",
        category: "Food",
      },
      {
        item_name: "Direct Deposit",
        amount: 500,
        date: " Novemeber 7",
        from: "Stockx",
        category: "Income",
      },
      {
        item_name: "Rent",
        amount: -2000,
        date: " November 22",
        from: "Pursuit Realty inc.",
        category: "Rent",
      },
      {
        item_name: "Gas Charge",
        amount: -100,
        date: " November 23",
        from: "BP Gas",
        category: "Transportation",
      },
    ]